#!/usr/bin/python

import os
env = Environment(ENV = os.environ)
env['CC']='gcc'
env['CXX']='g++'

basedir = os.getcwd()
env.Append(CPPPATH = [basedir])
#env.Append(LIBPATH = ['/workspace/opencv/build/x64/vc11/lib'])
env.Append(LIBS = ['tbb','m'])
sources = [
'nld_sys.cpp',
'le_solver.cpp',
'main.cpp',
'time_series.cpp',
'systems/lorenz.cpp',
'systems/rossler.cpp',
'systems/fhn.cpp',
]


env.Append(CPPFLAGS="-O0 -g -std=gnu++11")
env.Program(target="nld", source=sources)
